project_id = "wvfwnnujxvaukwrtydac"

[functions.submit-request]
enabled = true
verify_jwt = false
entrypoint = "./functions/submit-request/index.ts"

[functions.manage-request]
enabled = true
verify_jwt = false
entrypoint = "./functions/manage-request/index.ts"

[functions.sync-google-calendar]
enabled = true
verify_jwt = false
entrypoint = "./functions/sync-google-calendar/index.ts"
